edition = "2021"
max_width = 120
reorder_imports = true
struct_lit_width = 60
struct_variant_width = 60

# struct_field_align_threshold = 40
# comment_width = 120
# fn_single_line = false
# imports_layout = "HorizontalVertical"
# match_arm_blocks = false
# overflow_delimited_expr = true
# imports_granularity = "Crate"
